### ISSUE TITLE
Integration with Spring Boot

### ISSUE THREAD

**Issue by olgakorichkovskaya** [bazar-nazar/pgjson#3]
Entity: 

``` java
@Entity
@TypeDefs({@TypeDef( name= "JsonObject", typeClass = demo.Custom.class)})
public class Product {

    @Id
    @GeneratedValue
    public Integer id;
   private Custom custom;

    @Type(type = "JsonObject")
    public Custom getCustom() {
        return custom;
    }

    public void setCustom(Custom custom) {
        this.custom = custom;
    }
}
```

POJO:

``` java
public class Custom extends PGJsonObject {
...
}
```

I get an exception: 

```
Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]:
...
Caused by: java.lang.NoClassDefFoundError: Could not initialize class demo.Custom*
```

Maybe the cause of problem is Spring Boot (v1.2.0.RC1)?

**Comment by bazar-nazar** [comment]
Are you sure, that Spring configured correctly? Can i take look on your project? Or it is not public? Any way, i'll try to do Spring Boot sample tomorrow

**Comment by olgakorichkovskaya** [comment]
Hi, thanks for quick response!
I add an demo project with some tests: [GitHub](https://github.com/olgakorichkovskaya/pgjson-spring-boot-using-demo)

It is interesting, that test works well, but real application don't. It seem like there is a problem with Spring Boot initialization. 
And  I didn't manage with right configuration of Map and HashMap. Perhaps you could point out my mistake. 

Thank you for this project, really useful.

**Comment by bazar-nazar** [comment]
Hi.
I looked through your project, and didn't find any problems. I had same problem as you in IDE, but if i build project with "clean install" and then run jar from target with java -jar everything is all right. 
So, in my opinion, the reason is IDE settings.
What IDE do you use? how do you run your application?

Please let me know, if you can give me some additional information.

Thanks.

**Comment by olgakorichkovskaya** [comment]
Hi,

I use IntelliJ Idea 14.0.1.
But when I build with  "clean install"  and deploy to already runTomCat (7.0.54) ready war file - I get this problem also. As for problem connected with container somehow.

**Comment by bazar-nazar** [comment]
But your pom have only profile for standalone jar build. Can you show your pom for war build?

**Comment by rigidsh** [comment]
I have same problem with jar spring boot project. 
I fix it by add dependency to my pom:

```
<dependency>
    <groupId>org.codehaus.jackson</groupId>
    <artifactId>jackson-mapper-asl</artifactId>
</dependency>
```
