### ISSUE TITLE
Support for JPA 2.1 AttributeConverter - store String as json column

### ISSUE THREAD

**Issue by ieugen** [bazar-nazar/pgjson#5]
Hello, 

I'm using JPA 2.1 AttributeConverter to store custom objects/lists as JSON, However PgJSON does not seem to take the Converter into account.  Am I missing something?

**Comment by bazar-nazar** [comment]
Hello,

The reason of issue, is that inside of JSON object hibernate mechanisms doesnt work at all. Json object is serialized and deserialized via jackson object mapper. So u need to look, how to make your custom convert using jackson. 
Maybe you will need to get an access to jackson object mapper, to register custom converters. U can freely access it in child of PGJsonObject. Object mapper is protected field.

**Comment by ieugen** [comment]
Sounds complicated. What I wish to do is use AttributeConverter to convert whatever to String and store the result in a JSON column. However, when I try that, hibernate/jdbc complaints that it can't store varchar as json --> PostgreSQL type constraints.

**Comment by bazar-nazar** [comment]
Maybe i misunderstand what do u want to do. Can you provide me with some code and configuration samples?

**Comment by ieugen** [comment]
Sure.

My entity, notice **answers** field is converted with **AttributeConverter** to String and **columnDefinition="varchar"**

```
@Entity
@Table(name = "items_content", uniqueConstraints = {
    @UniqueConstraint(name = "unique_translation_per_item", columnNames = {"locale", "item_id"})
})
public class ItemContent extends AbstractEntity {
    @Convert(converter = LocaleToStringConverter.class)
    private Locale locale;
    @Column(columnDefinition = "varchar")
    private String text;
    @Convert(converter = AnswerListToJson.class)
    @Column(columnDefinition = "varchar")
    private List<String> answers;
}
```

The converter encodes Java object to JSON String .

```
@Convert
public class AnswerListToJson implements AttributeConverter<List<String>, String> {
    @Override
    public String convertToDatabaseColumn(List<String> attribute) {
        if (attribute == null) {
            return null;
        } else {
            return Json.encode(attribute);
        }
    }
    @Override
    public List<String> convertToEntityAttribute(String dbData) {
        if (dbData == null) {
            return new ArrayList<>();
        } else {
            return Json.decodeValue(dbData, List.class);
        }
    }
}
```

The issue: 

I wish to use **columnDefinition="json"** so I can leverage PostgreSQL indexes and querying but If I do that, the code fails at runtime. I'm using hibernate 5.0.2 (PostgreSQL94Dialect) with Spring data 1.9.0, Jackson 2.6.2 and postgresql driver 9.4-1201-jdbc41

**Comment by bazar-nazar** [comment]
I don't understand idea of your code. First of all, I cant see where you going to use PGJson Library. You are trying just to convert your field to string, and write it to field of varchar type. Obviously it will not give u any benefits of postgres json type. Why hibernate is up to your JPA configurations. 

Any way, if you want to use PGJson library you need to do next steps.
First of all wrap your List of answers into object which should extend PGJsonObject (There a way to store collection itself, but unfortunately it is not stable).

```
public class Answers extends PGJsonObject {
    private List<String> answers;
    //accessor methods
}
```

After that use this wrapper object except list.

```
@Entity
@Table(name = "items_content", uniqueConstraints = {
    @UniqueConstraint(name = "unique_translation_per_item", columnNames = {"locale", "item_id"})
})
public class ItemContent extends AbstractEntity {
    @Convert(converter = LocaleToStringConverter.class)
    private Locale locale;
    @Column(columnDefinition = "varchar")
    private String text;

    @Type(type = "your.package.name.Answers")
    private Answers answers;
}
```

Notice, that u do not need columnDefinition param.  It should automatically set column type to json. but you need to specify path to class of wrapper object, to make JPA know about it.

**Comment by ieugen** [comment]
Thank your for your answer. What bothers me  with the approach you showed is that I have to use a wrapper object that extends PGJsonObject (custom/proprietary api). This is need just to convert the data to String (JSON is essentially String) and store that String into a column of type json. 

What I'm looking for is a way to do specify that the result of the attribute converter should be stored in a **json** column. I haven't had a chance to dig very deep into hibernate/jpa api to figure out how to do this, but I believe it is possible. 

I hope it's a bit clearer. If I find some time to dig deeper into this, I will come back with details.

Thank you again and have a nice day,

**Comment by bazar-nazar** [comment]
Its not a proprietary API,  its API from this project. And u obviously need to use it if u want to use my project. Its all opensource under apache licence and it is to save your time. If u want to know how i store into JSON field u can just look into source code. Here u can find PGJsonObject source. https://github.com/bazar-nazar/pgjson/blob/master/src/main/java/com/bazarnazar/pgjson/PGJsonObject.java. 
Ofc u can do all of it by yourself, But then the question is, why do u need my project?
